#!/bin/bash

echo "Building Atlas Project"

g++ -I/usr/include/python2.7 -I /home/root/Desktop/Quadvisio/ /home/root/Desktop/Quadvisio/Sensors/adxl345.cpp /home/root/Desktop/Quadvisio/motor/motorPWM.cpp /home/root/Desktop/Quadvisio/motor/pyembed.cpp main.cpp -L/usr/lib/python2.7/config -Xlinker -export-dynamic -lpython2.7 -lm -lpthread -lutil -o atlas
