######################################################################
# Automatically generated by qmake (3.0) ons sep 3 19:18:07 2014
######################################################################

TEMPLATE = app
TARGET = Qvis
DEPENDPATH += .
INCLUDEPATH += /usr/include/opencv2
QT+=network
QT+= webkit
QT+=opengl
# Input
HEADERS += controller.h glwidget.h layout.h model.h
SOURCES += controller.cpp glwidget.cpp layout.cpp main.cpp model.cpp
