######################################################################
# Automatically generated by qmake (2.01a) sön maj 11 20:29:35 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h
SOURCES += gui.cpp main.cpp

ICON = qvis_icon2.icns