#!/bin/bash

echo "Building the sensor class project"

g++ -O2 -I /home/root/Desktop/Quadvisio/ /home/root/Desktop/Quadvisio/Kalman/kalman.cpp sensors.cpp adxl345.cpp mpu6050.cpp l3g4200d.cpp -o testSensor
