#!/bin/bash

echo "Building the sensor class project"

g++ -O2 -I /home/ubuntu/Quadvisio/ /home/ubuntu/Quadvisio/Kalman/kalman.cpp sensors.cpp l3g4200d.cpp adxl345.cpp hmc5883l.cpp bmp085.cpp -o testSensor -std=gnu++11
