#!/bin/bash

echo "Building Atlas test software…"

g++ -O2 -W -I /root/code/Quadvisio/ /root/code/Quadvisio/Sensors/adxl345.cpp /root/code/Quadvisio/Kalman/kalman.cpp /root/code/Quadvisio/QuadLib/QuadCore.cpp /root/code/Quadvisio/QuadLib/QuadPWM.cpp main.cpp Com.cpp SensorManager.cpp MPU6050.cpp Motor.cpp Controller.cpp I2Cdev.cpp -o Atlas -pthread -std=c++11
