#!/bin/bash

echo "Building Atlas…”

g++ -O2 -W -I /home/root/Desktop/Quadvisio/ /home/root/Desktop/Quadvisio/Quadlib/QuadCore.cpp /home/root/Desktop/Quadvisio/Quadlib/QuadPWM.cpp main.cpp Com.cpp SensorManager.cpp MPU6050.cpp Motor.cpp Controller.cpp I2Cdev.cpp -o Atlas `pkg-config --cflags --libs opencv` -pthread -std=c++11
